# Generated by Django 4.2.20 on 2025-03-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_permission',
            field=models.BooleanField(default=False),
        ),
    ]
