# Generated by Django 4.2.20 on 2025-03-15 13:42

from django.db import migrations
from django.contrib.auth.models import User

from staff.models import Staff


def create_staff(apps, schema_editor):
    phone_number = "+7 (777) 123 45 67"
    password = "12345678"
    user = User.objects.create(username=phone_number)
    user.set_password(password)
    user.save()
    Staff.objects.create(account=user,
                         fullname="staff",
                         phone_number=phone_number,
                         password=password)


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_staff, migrations.RunPython.noop),
    ]
