# Generated by Django 4.2.20 on 2025-03-13 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_video_progress', models.TextField(default='[]')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='client.client')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_courses', to='course.course')),
            ],
            options={
                'unique_together': {('client', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ClientLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('closed', 'Закрыт'), ('opened', 'Открыт'), ('passed', 'Пройден')], default='closed', max_length=25)),
                ('client_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='client_course.clientcourse')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_lessons', to='course.lesson')),
            ],
            options={
                'unique_together': {('client_course', 'lesson')},
            },
        ),
    ]
